# Generated by Django 5.2.1 on 2025-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_remove_post_dislike_count_remove_post_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=0),
        ),
    ]
